### PR TITLE
Add pagination to the "HOME" page to speed up rendering times

### PR DESCRIPTION
**Pull request by lukezsmith**
Pagination added to home page as a fix for issue #1. 
Tested all functionality with/without wallet connection and no issues.

### CODE REVIEW

**Review by 0xTranqui — CHANGES_REQUESTED** [review]
this looks great! one update I'd like to see before merging I have is adjusting the standard "asksPerPage" value on line 215 of pages/index.js to somewhere between 15-25 (5 seems to low to me -- since it requires user to click through 115 ish pages to see all NFTs).

**Comment by lukezsmith** [comment]
> this looks great! one update I'd like to see before merging I have is adjusting the standard "asksPerPage" value on line 215 of pages/index.js to somewhere between 15-25 (5 seems to low to me -- since it requires user to click through 115 ish pages to see all NFTs).

Sure, this is an easy fix.  Another option could be a selector somewhere (i.e maybe in the header, next to the advanced search button, etc) from which the user can select the number of results to display per page, e.g 10, 20, 50, etc. 

Let me know your thoughts on the idea!

**Comment by 0xTranqui** [comment]
> Sure, this is an easy fix. Another option could be a selector somewhere (i.e maybe in the header, next to the advanced search button, etc) from which the user can select the number of results to display per page, e.g 10, 20, 50, etc.
> 
> Let me know your thoughts on the idea!

Yea was gonna suggest that but didn't want to ask too much. Maybe just add a "results per page" dropdown (in same styling as the others (check out fieldsort.jsx for template) as a new component that starts at a standard (10?) and then gives optionality as u mentioned? Also happy to merge this fix right away hardcoded to 15 and then add in the dropdown as a seperate PR. wtv u wanna do cool with me

**Comment by lukezsmith** [comment]
> > Sure, this is an easy fix. Another option could be a selector somewhere (i.e maybe in the header, next to the advanced search button, etc) from which the user can select the number of results to display per page, e.g 10, 20, 50, etc.
> > Let me know your thoughts on the idea!
> 
> Yea was gonna suggest that but didn't want to ask too much. Maybe just add a "results per page" dropdown (in same styling as the others (check out fieldsort.jsx for template) as a new component that starts at a standard (10?) and then gives optionality as u mentioned? Also happy to merge this fix right away hardcoded to 15 and then add in the dropdown as a seperate PR. wtv u wanna do cool with me

Okay, I have just pushed changes that increase results per page to 15 for now. Will implement the dropdown in the next few days when I have a bit more time. I've also hidden the pagination when there are zero results as you mentioned in issue #1 . 

I also added a change that reduces the amount of page numbers displayed in the pagination as it overflows on smaller viewports with the 5 that was initially set: 
Screenshot 2022-06-01 at 22 38 04

I have changed it to 3 to stop it overflowing so much:
Screenshot 2022-06-01 at 22 38 19

Again, this can be changed back if you prefer

**Review by 0xTranqui — APPROVED** [review]
looks great! first PR in the books

**Review by 0xTranqui — APPROVED** [review]
thanks for fixing this

**Pull request merged**
